version: '3.8'
services:
  backend:
    build: ./backend
    # The backend is no longer directly exposed to the internet

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Add this line below
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      # Expose port 3000 on the host, mapping to port 3000 inside nginx
      - "3000:80"
    volumes:
      # Mount our nginx.conf file into the container
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend